fixtures:
    repositories:
      stdlib:
        repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
        ref: 4.25.1
      apt:
        repo: https://github.com/puppetlabs/puppetlabs-apt.git
        ref: 4.3.0
      inifile:
        repo: https://github.com/puppetlabs/puppetlabs-inifile.git
        ref: 2.4.0
      grafana:
        repo: https://github.com/voxpupuli/puppet-grafana.git
        ref: v4.5.0
      yumrepo:
        repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
        ref: 1.0.2
    forge_modules:
      healthcheck: "puppet/healthcheck"
